FROM eclipse-temurin:17-jdk-alpine AS builder

WORKDIR /app

COPY pom.xml ./
COPY .mvn/ .mvn/
COPY mvnw ./
RUN chmod +x mvnw

RUN ./mvnw dependency:go-offline -B

COPY src ./src

RUN ./mvnw clean package -DskipTests

FROM eclipse-temurin:17-jre-alpine

WORKDIR /app

COPY --from=builder /app/target/dogadaj-0.0.1-SNAPSHOT.jar app.jar

EXPOSE 8080

CMD ["java", "-XX:+UseContainerSupport", "-Xmx512m", "-jar", "app.jar"]
